included:
  - ArrvisCore

excluded:
  - Carthage/

disabled_rules:
  - force_cast
  - force_try

file_length:
  warning: 250
  error: 300
type_body_length:
  warning: 100
  error: 200
function_body_length:
  warning: 100
  error: 200
function_parameter_count:
  warning: 5
  error: 10
line_length:
  warning: 120
  error: 200
identifier_name:
  min_length: 1
