included:
  - ArrvisCore

excluded:
  - Carthage/

disabled_rules:
  - force_cast
  - force_try
  - unused_setter_value

file_length:
  warning: 250
  error: 300
type_body_length:
  warning: 100
  error: 200
function_body_length:
  warning: 100
  error: 200
function_parameter_count:
  warning: 10
  error: 15
line_length:
  warning: 120
  error: 200
identifier_name:
  min_length: 1
cyclomatic_complexity:
  ignores_case_statements: true
large_tuple:
  warning: 4
  error: 6
