included:
  - Root

excluded:
  - Carthage/
  - Root/Application/R.generated.swift
  - Root/GraphQL/API.swift
  - Root/Application/AppScreens.swift

disabled_rules:
  - force_cast
  - nesting

type_name:
  min_length: 3
  max_length: 50
file_length:
  warning: 300
  error: 350
type_body_length:
  warning: 140
  error: 150
function_body_length:
  warning: 100
  error: 200
function_parameter_count:
  warning: 20
  error: 25
line_length:
  warning: 300
  error: 350
identifier_name:
  min_length: 1
cyclomatic_complexity:
  ignores_case_statements: true
large_tuple:
  warning: 5
  error: 10
